"""
Django settings for PanelAdmin project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fq&ok%4yub^_0wm#m0t*z4646tkp2f^8id&tz$)&!7b!n+xrpj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'telegramadmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "jalali_date",
    
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'PanelAdmin.urls'

TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [BASE_DIR / "telegramadmin" / "templates"],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                ],
            },
        },
    ]

WSGI_APPLICATION = 'PanelAdmin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'pr_telegrambot',
        'USER': 'root',
        'PASSWORD': 'mirzaei.mohamad1387@gmail.com',
        'HOST' : 'localhost',
        "PORT": "3306"
    }
}

from django.urls import reverse_lazy
from django.templatetags.static import static

UNFOLD = {
    "LANG" : "en",
    "SITE_TITLE": "داریک",
    "SITE_HEADER": "داریک",
    "SITE_SUBHEADER": "پنل مدیریت ربات داریک",
    "DASHBOARD_CALLBACK" : "telegramadmin.utils.dashboard_callback",
    "STYLES" : [
            lambda request : static("css/admin.css"),
        ],
    "RTL" : True, 
    "SIDEBAR": {
        "show_search": False,  # Search in applications and models names
        "command_search": False,  # Replace the sidebar search with the command search
        "show_all_applications": False,  # Dropdown with all applications and models
        
        "navigation": [
            {
                "title": "مدیریت ربات",
                "icon" : "settings",
                "separator": True,  # Top border
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": "اطلاعات ربات",
                        "icon": "fiber_manual_record",  # Supported icon set: https://fonts.google.com/icons
                        "link": reverse_lazy("admin:telegramadmin_bot_changelist"),
                        
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": "اعضای ربات",
                        "icon": "fiber_manual_record",
                        "link": reverse_lazy("admin:telegramadmin_botmember_changelist")
                        
                    },
                ],
            },
            {
                "title": "داریک",
                "icon" : "settings",
                "collapsible": True,
                "items": [
                    {
                        "title": "ارزها",
                        "icon": "fiber_manual_record",
                        "link": reverse_lazy("admin:telegramadmin_currency_changelist"),
                    },
                    {
                        "title": "بازه های زمانی",
                        "icon": "fiber_manual_record",
                        "link": reverse_lazy("admin:telegramadmin_timeframe_changelist"),
                    },
                    {
                        "title": "زمان های کاربران",
                        "icon": "fiber_manual_record",
                        "link": reverse_lazy("admin:telegramadmin_framemember_changelist"),
                    },
                    {
                        "title": "تحلیل ها",
                        "icon": "fiber_manual_record",
                        "link": reverse_lazy("admin:telegramadmin_analysis_changelist"),
                    },
                    {
                        "title": "تحلیل کاربران",
                        "icon": "fiber_manual_record",
                        "link": reverse_lazy("admin:telegramadmin_analysismember_changelist"),
                    },
                ]
            },
        ],
    },
}






JALALI_DATE_DEFAULTS = {
    'DATE_FORMAT': '%Y/%m/%d',
    'DATETIME_FORMAT': '%H:%M:%S _ %Y/%m/%d',
    'SHOW_TIME': False,  # برای اینکه فقط تاریخ نشون بده نه زمان
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fa'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
ADMIN_SITE = "telegramadmin.admin.admin_site"

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
import os 
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = "/media/"
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
